version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:80"
    container_name: local-nginx
    volumes:
      - ./docker/hosts:/etc/nginx/conf.d
      - ./src:/var/src
      - ./docker/logs/nginx:/var/log/nginx
    links:
      - php
  php:
    image: php:8.2-fpm
    volumes:
      - ./src:/var/src
  database:
    image: mysql
    cap_add:
      - SYS_NICE
    ports:
      - "3306:3306"
    command:
      #--max_allowed_packet=32505856
      --sql_mode='NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
      --default-authentication-plugin=mysql_native_password
      --sort_buffer_size=256000000
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always

volumes:
  db_data:
